pipeline {
    agent any

    stages {
        stage ('GetProject') {
            steps {
                 git branch: 'main', url: 'https://github.com/JamesSheridanCode/MavenTest.git'
            }
        }
        stage ('build') {
            steps {
                sh 'mvn clean:clean'
                sh 'mvn dependency:copy-dependencies'
                sh 'mvn compiler:compile'
            }
        }
        stage ('Package') {
            steps {
                sh 'mvn package'
            }
        }
        stage ('Exec') {
                    steps {
                        sh 'mvn exec:java'
                    }
                }
    }
    post {
        success {
            archiveArtifacts allowEmptyArchive: true,
                artifacts: '**/ct5171_test1Maven*.jar'
        }
    }
}
//