pipeline {
    agent any

    stages {
        stage('GetProject') {
                    steps {
                        dir('ct5171_test1Maven') {  // Move into the correct subdirectory
                            git branch: 'main', url: 'https://github.com/JamesSheridanCode/MavenTest.git'
                        }
                    }
                }
                stage('Build') {
                    steps {
                        dir('ct5171_test1Maven') {  // Ensure the command runs in the correct directory
                            sh 'mvn clean install'
                        }
                    }
                }
        stage('Package') {
                    steps {
                        dir('ct5171_test1Maven') {  // Ensure the command runs in the correct directory
                            sh 'mvn package'
                        }
                    }
                }
        stage ('Exec') {
                    steps {
                        dir('ct5171_test1Maven') {
                        sh 'mvn exec:java' }
                    }
                }
    }
    post {
        success {
            archiveArtifacts allowEmptyArchive: true,
                artifacts: '**/ct5171_test1Maven*.jar'
        }
    }
}
//